// public is a keyword to define access level 
// know as access modifier, there are couple of them we will learn later
// class : indicate this is a class
// phone : identifier the name of the class
// { any code need to go in here, can not go outside }
// The moment a class exist, it can be a DataType
// meaning, you can create a variable of that type
// you can create a new instance (object) of that type and assign the variable
// and much more
public class Phone {
	// a phone has below
	// attributes or characteristics
	// brand, price, memorySize
	// string, decimal/integer/double, integer(because we use number and text)
	// this is a variable under a class = instanse variable | field 
	public String brand ; 
    public Decimal price ;
    public Integer memorySize ;
}