/* 
Declare and initialize an Integer variable. 
checks if a given integer is positive, negative, or zero. 
If the number is positive, the program should print "Positive." 
If the number is negative, the program should print “negative”
Else print Zero
*/
Integer score = 10 ; 
if(score > 0){      
    System.debug('Positive') ;
}else if(score < 0){
    System.debug('Negative') ;
}else{
    System.debug('Zero') ;
}